version: '3.8'
services:
  db-dev:
    image: postgres:13
    ports: 
      - 5434:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: menu_booking_dev
    networks: 
      - pacific  
  db-test:
    image: postgres:13
    ports: 
      - 5454:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: menu_booking_test
    networks: 
      - pacific     
networks:
  pacific:      